import { VStack, Text, Link as ChakraLink } from "@chakra-ui/react";
import Head from "next/head";
import Link from "next/link";

const links = [
  {
    label: "Soal Nomor 1-2",
    link: "/soal-pertama",
  },
  {
    label: "Soal Nomor 3-6",
    link: "soal-kedua",
  },
  {
    label: "Soal Nomor 7",
    link: "soal-ketiga",
  },
  {
    label: "Soal Nomor 8",
    link: "soal-keempat",
  },
  {
    label: "Soal Nomor 9",
    link: "soal-kelima",
  },
  {
    label: "Soal Nomor 10-11",
    link: "soal-keenam",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack align="start">
        {links.map((val) => (
          <ChakraLink key={val.label} as={Link} href={val.link}>
            {val.label}
          </ChakraLink>
        ))}
      </VStack>
    </>
  );
}
